spring:
  profiles:
    default: dev

properties:
  api:
    version: v1
  webClient:
    connectionTimeoutMsec: 5000
    maxInMemorySize: 4194304
  search:
    enableCache: true
    cacheExpireSec: 60
    cacheTimeoutMsec: 3000
    maxQueryPageSize: 300
    sources:
      kakao:
        name: kakao
        cachePageSize: 50
        restApiKey: KakaoAK d8831ca9fce59bb328e9bd160e28ec2b
        blog:
          url: https://dapi.kakao.com/v2/search/blog
        book:
          url: https://dapi.kakao.com/v3/search/book
      naver:
        name: naver
        cachePageSize: 100
        clientId: H4k64gJBoxn066T7pfjd
        clientSecret: J_5tDKIwWL
        blog:
          url: https://openapi.naver.com/v1/search/blog.json
  asyncTaskPool:
    maxPoolSize: 8
