spring:
  profiles:
    default: dev

logging:
  level:
    reactor:
      netty: debug

properties:
  api:
    version: v1
  webClient:
    connectionTimeout: 15s
    responseTimeout: 15s
    maxInMemorySizeKb: 262_144
    connPool:
      # async-request-num should be less than it
      maxConnectionNum: 40
      pendingAcquireTimeout: 1000ms
      pendingAcquireMaxCount: 5
      maxIdleTime: 30000ms
  search:
    enableCache: true
    cacheExpireSec: 60
    cacheTimeoutMsec: 3000
    maxQueryPageSize: 300
    sources:
      kakao:
        cachePageSize: 50
        restApiKey: KakaoAK d8831ca9fce59bb328e9bd160e28ec2b
        blog:
          url: https://dapi.kakao.com/v2/search/blog
        book:
          url: https://dapi.kakao.com/v3/search/book
      naver:
        cachePageSize: 100
        clientId: H4k64gJBoxn066T7pfjd
        clientSecret: J_5tDKIwWL
        blog:
          url: https://openapi.naver.com/v1/search/blog.json
  asyncTaskPool:
    maxPoolSize: 8
